import PrivateBluetoothSdkModule from "./_private/BluetoothSdkModule"
import type {
  BluetoothSdkEventListener,
  BluetoothSdkEventName,
  BluetoothSdkPublicModule,
} from "./BluetoothSdk.types"

const PUBLIC_EVENT_NAMES = new Set<BluetoothSdkEventName>([
  "log",
  "device_discovered",
  "default_device_changed",
  "glasses_not_ready",
  "button_press",
  "touch_event",
  "head_up",
  "voice_activity_detection_status",
  "speaking_status",
  "battery_status",
  "local_transcription",
  "wifi_status_change",
  "hotspot_status_change",
  "hotspot_error",
  "photo_response",
  "gallery_status",
  "compatible_glasses_search_stop",
  "swipe_volume_status",
  "switch_status",
  "rgb_led_control_response",
  "pair_failure",
  "audio_pairing_needed",
  "audio_connected",
  "audio_disconnected",
  "mic_pcm",
  "mic_lc3",
  "stream_status",
  "keep_alive_ack",
])

const addListener: BluetoothSdkPublicModule["addListener"] = (eventName, listener) => {
  if (!PUBLIC_EVENT_NAMES.has(eventName)) {
    throw new Error(
      `Unsupported BluetoothSdk event "${eventName}". Use @mentra/bluetooth-sdk/react for status state.`,
    )
  }
  return PrivateBluetoothSdkModule.addListener(
    eventName,
    listener as BluetoothSdkEventListener<BluetoothSdkEventName>,
  )
}

export const BluetoothSdk: BluetoothSdkPublicModule = Object.freeze({
  addListener,
  getDefaultDevice: PrivateBluetoothSdkModule.getDefaultDevice.bind(PrivateBluetoothSdkModule),
  setDefaultDevice: PrivateBluetoothSdkModule.setDefaultDevice.bind(PrivateBluetoothSdkModule),
  clearDefaultDevice: PrivateBluetoothSdkModule.clearDefaultDevice.bind(PrivateBluetoothSdkModule),
  startScan: PrivateBluetoothSdkModule.startScan.bind(PrivateBluetoothSdkModule),
  stopScan: PrivateBluetoothSdkModule.stopScan.bind(PrivateBluetoothSdkModule),
  scan: PrivateBluetoothSdkModule.scan.bind(PrivateBluetoothSdkModule) as BluetoothSdkPublicModule["scan"],
  connect: PrivateBluetoothSdkModule.connect.bind(PrivateBluetoothSdkModule),
  connectDefault: PrivateBluetoothSdkModule.connectDefault.bind(PrivateBluetoothSdkModule),
  cancelConnectionAttempt: PrivateBluetoothSdkModule.cancelConnectionAttempt.bind(PrivateBluetoothSdkModule),
  disconnect: PrivateBluetoothSdkModule.disconnect.bind(PrivateBluetoothSdkModule),
  forget: PrivateBluetoothSdkModule.forget.bind(PrivateBluetoothSdkModule),
  displayText: PrivateBluetoothSdkModule.displayText.bind(PrivateBluetoothSdkModule),
  clearDisplay: PrivateBluetoothSdkModule.clearDisplay.bind(PrivateBluetoothSdkModule),
  showDashboard: PrivateBluetoothSdkModule.showDashboard.bind(PrivateBluetoothSdkModule),
  setDashboardPosition: PrivateBluetoothSdkModule.setDashboardPosition.bind(PrivateBluetoothSdkModule),
  setHeadUpAngle: PrivateBluetoothSdkModule.setHeadUpAngle.bind(PrivateBluetoothSdkModule),
  setScreenDisabled: PrivateBluetoothSdkModule.setScreenDisabled.bind(PrivateBluetoothSdkModule),
  requestWifiScan: PrivateBluetoothSdkModule.requestWifiScan.bind(PrivateBluetoothSdkModule),
  sendWifiCredentials: PrivateBluetoothSdkModule.sendWifiCredentials.bind(PrivateBluetoothSdkModule),
  forgetWifiNetwork: PrivateBluetoothSdkModule.forgetWifiNetwork.bind(PrivateBluetoothSdkModule),
  setHotspotState: PrivateBluetoothSdkModule.setHotspotState.bind(PrivateBluetoothSdkModule),
  setGalleryModeEnabled: PrivateBluetoothSdkModule.setGalleryModeEnabled.bind(PrivateBluetoothSdkModule),
  setVoiceActivityDetectionEnabled: PrivateBluetoothSdkModule.setVoiceActivityDetectionEnabled.bind(PrivateBluetoothSdkModule),
  setButtonPhotoSettings: PrivateBluetoothSdkModule.setButtonPhotoSettings.bind(PrivateBluetoothSdkModule),
  setButtonVideoRecordingSettings: PrivateBluetoothSdkModule.setButtonVideoRecordingSettings.bind(PrivateBluetoothSdkModule),
  setButtonCameraLed: PrivateBluetoothSdkModule.setButtonCameraLed.bind(PrivateBluetoothSdkModule),
  setButtonMaxRecordingTime: PrivateBluetoothSdkModule.setButtonMaxRecordingTime.bind(PrivateBluetoothSdkModule),
  setCameraFov: PrivateBluetoothSdkModule.setCameraFov.bind(PrivateBluetoothSdkModule),
  queryGalleryStatus: PrivateBluetoothSdkModule.queryGalleryStatus.bind(PrivateBluetoothSdkModule),
  requestPhoto: PrivateBluetoothSdkModule.requestPhoto.bind(PrivateBluetoothSdkModule),
  startVideoRecording: PrivateBluetoothSdkModule.startVideoRecording.bind(PrivateBluetoothSdkModule),
  stopVideoRecording: PrivateBluetoothSdkModule.stopVideoRecording.bind(PrivateBluetoothSdkModule),
  startStream: PrivateBluetoothSdkModule.startStream.bind(PrivateBluetoothSdkModule),
  stopStream: PrivateBluetoothSdkModule.stopStream.bind(PrivateBluetoothSdkModule),
  keepStreamAlive: PrivateBluetoothSdkModule.keepStreamAlive.bind(PrivateBluetoothSdkModule),
  setMicState: PrivateBluetoothSdkModule.setMicState.bind(PrivateBluetoothSdkModule),
  setPreferredMic: PrivateBluetoothSdkModule.setPreferredMic.bind(PrivateBluetoothSdkModule),
  setOwnAppAudioPlaying: PrivateBluetoothSdkModule.setOwnAppAudioPlaying.bind(PrivateBluetoothSdkModule),
  getGlassesMediaVolume: PrivateBluetoothSdkModule.getGlassesMediaVolume.bind(PrivateBluetoothSdkModule),
  setGlassesMediaVolume: PrivateBluetoothSdkModule.setGlassesMediaVolume.bind(PrivateBluetoothSdkModule),
  rgbLedControl: PrivateBluetoothSdkModule.rgbLedControl.bind(PrivateBluetoothSdkModule),
  requestVersionInfo: PrivateBluetoothSdkModule.requestVersionInfo.bind(PrivateBluetoothSdkModule),
})

export default BluetoothSdk

export {
  DeviceModels,
  isBusyGlassesConnectionStatus,
  isConnectedGlassesConnectionStatus,
  isConnectedWifiStatus,
  isEnabledHotspotStatus,
  isReadyGlassesConnectionStatus,
} from "./BluetoothSdk.types"

export type {
  AudioConnectedEvent,
  AudioDisconnectedEvent,
  AudioPairingNeededEvent,
  BatteryStatusEvent,
  BluetoothSdkEvent,
  BluetoothSdkEventListener,
  BluetoothSdkEventMap,
  BluetoothSdkEventName,
  BluetoothSdkPublicModule as BluetoothSdkModule,
  BluetoothSdkSubscription,
  ButtonPhotoSize,
  ButtonPressEvent,
  CameraFov,
  CompatibleGlassesSearchStopEvent,
  ConnectOptions,
  ConnectedGlassesConnectionStatus,
  ConnectedWifiStatus,
  Device,
  DeviceModel,
  EnabledHotspotStatus,
  GalleryStatusEvent,
  GlassesConnectionStatus,
  GlassesMediaVolumeGetResult,
  GlassesMediaVolumeSetResult,
  GlassesNotReadyEvent,
  HeadUpEvent,
  HotspotErrorEvent,
  HotspotStatus,
  HotspotStatusChangeEvent,
  KeepAliveAckEvent,
  LocalTranscriptionEvent,
  LogEvent,
  MicLc3Event,
  MicMode,
  MicPcmEvent,
  MicPreference,
  PairFailureEvent,
  PhotoCompression,
  PhotoResponseEvent,
  PhotoSize,
  RgbLedAction,
  RgbLedColor,
  RgbLedControlResponseEvent,
  ScanModelOptions,
  ScanOptions,
  ScanResultsCallback,
  SpeakingStatusEvent,
  StreamAudioConfig,
  StreamKeepAliveRequest,
  StreamStartRequest,
  StreamStatusEvent,
  StreamStatusLifecycleState,
  StreamStatusReconnectState,
  StreamStatusState,
  StreamVideoConfig,
  SwipeVolumeStatusEvent,
  SwitchStatusEvent,
  TouchEvent,
  VoiceActivityDetectionStatusEvent,
  WifiSearchResult,
  WifiStatus,
  WifiStatusChangeEvent,
} from "./BluetoothSdk.types"
